export const ERROR_CODES = {
  EMPTY_CONTENT: 'EMPTY_CONTENT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
} as const;
